markdown: redcarpet
permalink: /:year/:month/:day/:title/
url: http://morisunshine.com
author: morisunshine
pygments: true
safe: true
paginate: 16
auto: true
name: Morisunshine's Blog
author: morisunshine
email: sheldon.zen@gmail.com
duoshuo: morisunshine
weibo: 1626743220
github: morisunshine
paginate: 20 
truncate: 300 
about: "这里是我的博客。"

analytics :
  provider : google
  google : 
      tracking_id : 'UA-47868064-1'
  getclicky :
    site_id :
